# Generated by Django 5.1.4 on 2024-12-19 14:26

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Husband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('age', models.IntegerField()),
                ('wealth', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('husband', models.OneToOneField(default=myapp.models.get_default_husband, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.husband')),
            ],
        ),
    ]
