# Generated by Django 5.1.4 on 2024-12-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_course_students_student_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='husband',
            name='wealth',
        ),
        migrations.AddField(
            model_name='husband',
            name='wealth_in_usd',
            field=models.IntegerField(default=10),
        ),
    ]
