# Generated by Django 5.1.4 on 2024-12-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_husband_wealth_husband_wealth_in_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='husband',
            old_name='wealth_in_usd',
            new_name='wealth',
        ),
    ]
