# Generated by Django 5.1.4 on 2024-12-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
