# Generated by Django 5.1.4 on 2024-12-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
