# Generated by Django 5.1.4 on 2024-12-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone_no',
        ),
    ]
